### ISSUE TITLE
v2 error: class private methods are not enabled

### ISSUE THREAD

**Issue by nightire** [tracked-tools/tracked-built-ins#204] opened 2021-11-13 07:02 UTC
I saw this error after upgrading tracked-built-ins to v2.0.0:

```
Build Error (broccoli-persistent-filter:Babel > [Babel: tracked-built-ins]) in -private/object.js

/Users/nightire/Code/github.com/choice-form/mono-apps/packages/os-portal/-private/object.js: Class private methods are not enabled.
  65 |
  66 |   // @private
> 67 |   #readStorageFor(key) {
     |   ^
  68 |     let storage = this.#storages.get(key);
  69 |
  70 |     if (storage === undefined) {
```

It happens with both the latest version of classic ember-cli and embroider, I've already tried with @babel/plugin-proposal-private-methods plugin, but the same error remains.

**Comment by NullVoxPopuli** [comment] 2021-11-13 15:53
This appears to be a bug with ember-cli-babel, where it does not correctly use the plugins / preset / targets / browserlist available to the host app. 🤔

**Comment by chriskrycho** [comment] 2021-11-14 14:10
Nope, it's a misconfiguration in this addon; addons should handle this themselves because they cannot guarantee what the host will or won't be providing. I will publish a bug fix tomorrow. (Embroider will handle this differently: we will publish spec ES and let folks down stream further process based on their targets but for now this is the right place to fix.)

**Comment by chriskrycho** [comment] 2021-11-15 19:10
Possibly I’m wrong and there *is* an ember-cli-babel bug, as this appears to be resolving the correct version of `@babel/preset-env` etc. 🤔

**Comment by chriskrycho** [comment] 2021-11-17 15:28
I’ve upgraded to this in the big app at work and it works *just fine*. (I'll report this on the ember-cli-babel repo as well.)

**Comment by chriskrycho** [comment] 2021-11-17 17:06
We've confirmed this is an upstream issue. Closing accordingly.

**Closed by chriskrycho** 2021-11-17 17:06 UTC
